sudo: required
services: 
        - docker
before_install:
        - dcoker build -t ramesh/docker-react -f Dockerfile.dev .
script:          
        - docker run ramesh/docker-react npm run test -- --coverage


